import { READINESS_CATEGORIES, SCORE_SCALE } from "../constants/readiness-model";
import type { ActionError, ActionResult } from "../types/shared";
import type { ReadinessScores } from "../types/readiness";
export function requireString(value: unknown, fieldName: string, maxLength = 2000): ActionResult<string> { if (typeof value !== "string" || value.trim().length === 0) { return { ok: false, errors: [{ code: "MISSING_REQUIRED_FIELD", message: `${fieldName} is required and must be a non-empty string.`, field: fieldName }] }; } if (value.length > maxLength) { return { ok: false, errors: [{ code: "FIELD_TOO_LONG", message: `${fieldName} exceeds maximum length of ${maxLength}.`, field: fieldName }] }; } return { ok: true, data: value.trim() }; }
export function optionalString(value: unknown, fieldName: string, maxLength = 2000): ActionResult<string | undefined> { if (value === undefined || value === null || value === "") return { ok: true, data: undefined }; if (typeof value !== "string") { return { ok: false, errors: [{ code: "INVALID_TYPE", message: `${fieldName} must be a string.`, field: fieldName }] }; } if (value.length > maxLength) { return { ok: false, errors: [{ code: "FIELD_TOO_LONG", message: `${fieldName} exceeds maximum length of ${maxLength}.`, field: fieldName }] }; } return { ok: true, data: value.trim() }; }
export function requireNumberInRange(value: unknown, fieldName: string, min: number, max: number): ActionResult<number> { if (typeof value !== "number" || Number.isNaN(value)) { return { ok: false, errors: [{ code: "INVALID_TYPE", message: `${fieldName} must be a valid number.`, field: fieldName }] }; } if (value < min || value > max) { return { ok: false, errors: [{ code: "VALUE_OUT_OF_RANGE", message: `${fieldName} must be between ${min} and ${max}.`, field: fieldName }] }; } return { ok: true, data: value }; }
export function requireEnum<T extends string>(value: unknown, fieldName: string, validValues: readonly T[]): ActionResult<T> { if (typeof value !== "string" || !validValues.includes(value as T)) { return { ok: false, errors: [{ code: "INVALID_ENUM_VALUE", message: `${fieldName} must be one of: ${validValues.join(", ")}.`, field: fieldName }] }; } return { ok: true, data: value as T }; }
export function requireArray(value: unknown, fieldName: string): ActionResult<unknown[]> { if (!Array.isArray(value)) { return { ok: false, errors: [{ code: "INVALID_TYPE", message: `${fieldName} must be an array.`, field: fieldName }] }; } return { ok: true, data: value }; }
export function validateReadinessScores(scores: unknown): ActionResult<ReadinessScores> { if (typeof scores !== "object" || scores === null || Array.isArray(scores)) { return { ok: false, errors: [{ code: "INVALID_TYPE", message: "scores must be a JSON object.", field: "scores" }] }; } const result = {} as ReadinessScores; const errors: ActionError[] = []; const rawScores = scores as Record<string, unknown>; for (const category of READINESS_CATEGORIES) { const valResult = requireNumberInRange(rawScores[category], `scores.${category}`, SCORE_SCALE.min, SCORE_SCALE.max); if (!valResult.ok) { errors.push(...valResult.errors); } else if (!Number.isInteger(valResult.data)) { errors.push({ code: "INVALID_TYPE", message: `scores.${category} must be an integer.`, field: `scores.${category}` }); } else { result[category] = valResult.data; } } if (errors.length > 0) return { ok: false, errors }; return { ok: true, data: result }; }
export function collectErrors(...results: (ActionResult<unknown> | ActionError[])[]): ActionError[] { const collected: ActionError[] = []; for (const result of results) { if (Array.isArray(result)) { collected.push(...result); } else if (!result.ok) { collected.push(...result.errors); } } return collected; }
export function jsonError(errors: ActionError[], status = 400): Response { return Response.json({ ok: false, errors }, { status }); }
